template = {
    "en": {
        "start": "Welcome! Please choose your language",
        "share_location": "Please share your location or type the name of the city or country",
        "main": "Main menu",
        "choose_city": "You have chosen {}",
        "no_such_city": "No such city or country found",
        "current": "Current",
        "feels": "feels like",
        "wind": "Wind",
        "humidity": "Humidity",
        "pressure": "Pressure",
        "kph": "kph",
        "mmhg": "mmHg",
        "chance_of_rain": "Chance of Rain",
        "chance_of_snow": "Chance of Snow",
        "notify_menu": "Notification Menu",
        "choose_lang": "Choose language",
        "changed_lang": "Language was changed to English",
        "leave_feedback": "Leave your feedback",
        "feedback_success": "Feedback submitted successfully",
        "choose_hour": "Choose the time for notification",
        "added": "Added!",
        "deleted": "Deleted!",

        "main_btn": "🏠 Main menu",
        "share_loc_btn": "📍 Share locations",
        "weather_now_btn": "☀️ Weather Now",
        "weather_tomorrow_btn": "🌤 Tomorrow's Weather",
        "weather_7_btn": "🗓️ 7-Day Weather",
        "weather_14_btn": "🗓 14-Day Weather",
        "notify_btn": "🔔 My notifications",
        "location_btn": "📍 Change Location",
        "change_lang_btn": "🌐 Change Language",
        "feedback_btn": "📝 Send Feedback",
        "back_btn": "⬅️ Back",
        "add_btn": "⏰ Add",

        "Monday": "Monday",
        "Tuesday": "Tuesday",
        "Wednesday": "Wednesday",
        "Thursday": "Thursday",
        "Friday": "Friday",
        "Saturday": "Saturday",
        "Sunday": "Sunday",

        "January": "January",
        "February": "February",
        "March": "March",
        "April": "April",
        "May": "May",
        "June": "June",
        "July": "July",
        "August": "August",
        "September": "September",
        "October": "October",
        "November": "November",
        "December": "December",

        "sunny": "☀️ Sunny",
        "clear": "🌟 Clear",
        "partly cloudy": "⛅ Partly cloudy",
        "cloudy": "☁️ Cloudy",
        "overcast": "🌥️ Overcast",
        "mist": "🌫️ Mist",
        "patchy rain nearby": "🌦️ Patchy rain possible",
        "patchy snow possible": "🌨️ Patchy snow possible",
        "patchy sleet possible": "🌧️ Patchy sleet possible",
        "patchy freezing drizzle possible": "🧊 Patchy freezing drizzle possible",
        "thundery outbreaks possible": "⛈️ Thundery outbreaks possible",
        "blowing snow": "🌬️❄️ Blowing snow",
        "blizzard": "🌨️❄️ Blizzard",
        "fog": "🌁 Fog",
        "freezing fog": "🥶🌁 Freezing fog",
        "patchy light drizzle": "🌦️ Patchy light drizzle",
        "light drizzle": "🌦️ Light drizzle",
        "freezing drizzle": "❄️🌧️ Freezing drizzle",
        "heavy freezing drizzle": "❄️🌧️ Heavy freezing drizzle",
        "patchy light rain": "🌦️ Patchy light rain",
        "light rain": "🌧️ Light rain",
        "moderate rain at times": "🌧️ Moderate rain at times",
        "moderate rain": "🌧️ Moderate rain",
        "heavy rain at times": "🌧️ Heavy rain at times",
        "heavy rain": "🌧️🌧️ Heavy rain",
        "light freezing rain": "❄️🌧️ Light freezing rain",
        "moderate or heavy freezing rain": "❄️🌧️ Moderate or heavy freezing rain",
        "light sleet": "🌨️ Light sleet",
        "moderate or heavy sleet": "🌨️🌨️ Moderate or heavy sleet",
        "patchy light snow": "🌨️ Patchy light snow",
        "light snow": "❄️ Light snow",
        "patchy moderate snow": "🌨️ Patchy moderate snow",
        "moderate snow": "🌨️ Moderate snow",
        "patchy heavy snow": "❄️❄️ Patchy heavy snow",
        "heavy snow": "❄️❄️ Heavy snow",
        "ice pellets": "🧊 Ice pellets",
        "light rain shower": "🌦️ Light rain shower",
        "moderate or heavy rain shower": "🌧️🌦️ Moderate or heavy rain shower",
        "torrential rain shower": "🌧️🌧️🌧️ Torrential rain shower",
        "light sleet showers": "🌨️ Light sleet showers",
        "moderate or heavy sleet showers": "🌨️🌨️ Moderate or heavy sleet showers",
        "light snow showers": "🌨️ Light snow showers",
        "moderate or heavy snow showers": "🌨️🌨️ Moderate or heavy snow showers",
        "light showers of ice pellets": "🧊 Light showers of ice pellets",
        "moderate or heavy showers of ice pellets": "🧊🧊 Moderate or heavy showers of ice pellets",
        "patchy light rain with thunder": "⛈️ Patchy light rain with thunder",
        "moderate or heavy rain with thunder": "⛈️⛈️ Moderate or heavy rain with thunder",
        "patchy light snow with thunder": "🌩️❄️ Patchy light snow with thunder",
        "moderate or heavy snow with thunder": "🌩️❄️❄️ Moderate or heavy snow with thunder"

    },
    "ru": {
        "start": "Добро пожаловать! Пожалуйста, выберите нужный язык",
        "share_location": "Пожалуйста, поделитесь своим местоположением или введите название города или страны",
        "main": "Главное меню",
        "choose_city": "Вы выбрали {}",
        "no_such_city": "Такого города или страны не найдено",
        "current": "Текущая",
        "feels": "oщущается как",
        "wind": "Ветер",
        "humidity": "Влажность",
        "pressure": "Давление",
        "kph": "км/ч",
        "mmhg": "мм рт.ст.",
        "chance_of_rain": "Шанс дождя",
        "chance_of_snow": "Шанс снега",
        "notify_menu": "Меню уведомлений",
        "choose_lang": "Выберите язык",
        "changed_lang": "Язык был изменён на русский",
        "leave_feedback": "Оставьте ваш отзыв",
        "feedback_success": "Отзыв успешно оставлен",
        "choose_hour": "Выберите нужное время для отправки уведомления",
        "added": "Добавлено!",
        "deleted": "Удалено!",

        "main_btn": "🏠 Главное меню",
        "share_loc_btn": "📍 Поделиться местоположением",
        "weather_now_btn": "☀️ Погода сейчас",
        "weather_tomorrow_btn": "🌤️ Погода на завтра",
        "weather_7_btn": "🗓️ Прогноз на 7 дней",
        "weather_14_btn": "🗓️ Прогноз на 14 дней",
        "notify_btn": "🔔 Мои уведомления",
        "location_btn": "📍 Изменить местоположение",
        "change_lang_btn": "🌐 Изменить язык",
        "feedback_btn": "📝 Оставить отзыв",
        "back_btn": "⬅️ Назад",
        "add_btn": "⏰ Добавить",

        "Monday": "Понедельник",
        "Tuesday": "Вторник",
        "Wednesday": "Среда",
        "Thursday": "Четверг",
        "Friday": "Пятница",
        "Saturday": "Суббота",
        "Sunday": "Воскресенье",

        "January": "Января",
        "February": "Февраля",
        "March": "Марта",
        "April": "Апреля",
        "May": "Мая",
        "June": "Июня",
        "July": "Июля",
        "August": "Августа",
        "September": "Сентября",
        "October": "Октября",
        "November": "Ноября",
        "December": "Декабря",

        "sunny": "☀️ Ясно",
        "clear": "🌟 Безоблачно",
        "partly cloudy": "⛅ Малооблачно",
        "cloudy": "☁️ Облачно",
        "overcast": "🌥️ Пасмурно",
        "mist": "🌫️ Дымка",
        "patchy rain nearby": "🌦️ Возможен кратковременный дождь",
        "patchy snow possible": "🌨️ Возможен кратковременный снег",
        "patchy sleet possible": "🌧️ Возможен кратковременный мокрый снег",
        "patchy freezing drizzle possible": "🧊 Возможна ледяная морось",
        "thundery outbreaks possible": "⛈️ Возможны грозы",
        "blowing snow": "🌬️❄️ Метель",
        "blizzard": "🌨️❄️ Буран",
        "fog": "🌁 Туман",
        "freezing fog": "🥶🌁 Ледяной туман",
        "patchy light drizzle": "🌦️ Местами слабая морось",
        "light drizzle": "🌦️ Слабая морось",
        "freezing drizzle": "❄️🌧️ Ледяная морось",
        "heavy freezing drizzle": "❄️🌧️ Сильная ледяная морось",
        "patchy light rain": "🌦️ Местами слабый дождь",
        "light rain": "🌧️ Слабый дождь",
        "moderate rain at times": "🌧️ Местами умеренный дождь",
        "moderate rain": "🌧️ Умеренный дождь",
        "heavy rain at times": "🌧️ Местами сильный дождь",
        "heavy rain": "🌧️🌧️ Сильный дождь",
        "light freezing rain": "❄️🌧️ Слабый ледяной дождь",
        "moderate or heavy freezing rain": "❄️🌧️ Умеренный или сильный ледяной дождь",
        "light sleet": "🌨️ Слабый мокрый снег",
        "moderate or heavy sleet": "🌨️🌨️ Умеренный или сильный мокрый снег",
        "patchy light snow": "🌨️ Местами слабый снег",
        "light snow": "❄️ Слабый снег",
        "patchy moderate snow": "🌨️ Местами умеренный снег",
        "moderate snow": "🌨️ Умеренный снег",
        "patchy heavy snow": "❄️❄️ Местами сильный снег",
        "heavy snow": "❄️❄️ Сильный снег",
        "ice pellets": "🧊 Ледяные гранулы",
        "light rain shower": "🌦️ Кратковременный слабый дождь",
        "moderate or heavy rain shower": "🌧️🌦️ Кратковременный сильный дождь",
        "torrential rain shower": "🌧️🌧️🌧️ Ливень",
        "light sleet showers": "🌨️ Кратковременный слабый мокрый снег",
        "moderate or heavy sleet showers": "🌨️🌨️ Кратковременный сильный мокрый снег",
        "light snow showers": "🌨️ Кратковременный слабый снег",
        "moderate or heavy snow showers": "🌨️🌨️ Кратковременный сильный снег",
        "light showers of ice pellets": "🧊 Кратковременные осадки из льда",
        "moderate or heavy showers of ice pellets": "🧊🧊 Сильные осадки из льда",
        "patchy light rain with thunder": "⛈️ Местами слабый дождь с грозой",
        "moderate or heavy rain with thunder": "⛈️⛈️ Сильный дождь с грозой",
        "patchy light snow with thunder": "🌩️❄️ Местами слабый снег с грозой",
        "moderate or heavy snow with thunder": "🌩️❄️❄️ Сильный снег с грозой"
    }
    ,
    "uz": {
        "start": "Xush kelibsiz! Iltimos, tilni tanlang",
        "share_location": "Iltimos, joylashuvingizni yuboring yoki shahar yoki mamlakat nomini yozing",
        "main": "Asosiy menyu",
        "choose_city": "Siz {}ni tanladingiz",
        "no_such_city": "Bunday shahar yoki mamlakat topilmadi",
        "current": "Hozirgi",
        "feels": "his etiladi",
        "wind": "Shamol",
        "humidity": "Namlik",
        "pressure": "Bosim",
        "kph": "km/soat",
        "mmhg": "mm s.u.",
        "chance_of_rain": "Yomg'ir ehtimoli",
        "chance_of_snow": "Qor yog'ishi ehtimoli",
        "notify_menu": "Bildirishnomalar menyusi",
        "choose_lang": "Tilni tanlang",
        "changed_lang": "Til O'zbek tiliga o‘zgartirildi",
        "leave_feedback": "Fikringizni qoldiring",
        "feedback_success": "Fikringiz muvaffaqiyatli yuborildi",
        "choose_hour": "Bildirishnoma uchun vaqtni tanlang",
        "added": "Qo‘shildi!",
        "deleted": "O‘chirildi!",

        "main_btn": "🏠 Asosiy menyu",
        "share_loc_btn": "📍 Joylashuvni yuborish",
        "weather_now_btn": "☀️ Hozirgi ob-havo",
        "weather_tomorrow_btn": "🌤️ Ertangi ob-havo",
        "weather_7_btn": "🗓️ 7 kunlik ob-havo",
        "weather_14_btn": "🗓️ 14 kunlik ob-havo",
        "notify_btn": "🔔 Mening bildirishnomalarim",
        "location_btn": "📍 Joylashuvni o‘zgartirish",
        "change_lang_btn": "🌐 Tilni o‘zgartirish",
        "feedback_btn": "📝 Fikr qoldirish",
        "back_btn": "⬅️ Orqaga",
        "add_btn": "⏰ Qo‘shish",

        "Monday": "Dushanba",
        "Tuesday": "Seshanba",
        "Wednesday": "Chorshanba",
        "Thursday": "Payshanba",
        "Friday": "Juma",
        "Saturday": "Shanba",
        "Sunday": "Yakshanba",

        "January": "Yanvar",
        "February": "Fevral",
        "March": "Mart",
        "April": "Aprel",
        "May": "May",
        "June": "Iyun",
        "July": "Iyul",
        "August": "Avgust",
        "September": "Sentabr",
        "October": "Oktabr",
        "November": "Noyabr",
        "December": "Dekabr",

        "sunny": "☀️ Quyoshli",
        "clear": "🌟 Musaffo",
        "partly cloudy": "⛅ Qisman bulutli",
        "cloudy": "☁️ Bulutli",
        "overcast": "🌥️ Qorong‘u bulutli",
        "mist": "🌫️ Tuman",
        "patchy rain nearby": "🌦️ Yengil yomg‘ir ehtimoli",
        "patchy snow possible": "🌨️ Yengil qor ehtimoli",
        "patchy sleet possible": "🌧️ Yengil yomg‘ir va qor aralash",
        "patchy freezing drizzle possible": "🧊 Muzli yomg‘ir ehtimoli",
        "thundery outbreaks possible": "⛈️ Momaqaldiroq ehtimoli",
        "blowing snow": "🌬️❄️ Qor bo‘roni",
        "blizzard": "🌨️❄️ Qor bo‘roni (kuchli)",
        "fog": "🌁 Tuman",
        "freezing fog": "🥶🌁 Muzli tuman",
        "patchy light drizzle": "🌦️ Yengil yomg‘ir tomchilari",
        "light drizzle": "🌦️ Yengil yomg‘ir",
        "freezing drizzle": "❄️🌧️ Muzli yomg‘ir",
        "heavy freezing drizzle": "❄️🌧️ Kuchli muzli yomg‘ir",
        "patchy light rain": "🌦️ Yengil yomg‘ir (ba'zida)",
        "light rain": "🌧️ Yengil yomg‘ir",
        "moderate rain at times": "🌧️ O‘rtacha yomg‘ir (vaqti-vaqti bilan)",
        "moderate rain": "🌧️ O‘rtacha yomg‘ir",
        "heavy rain at times": "🌧️ Kuchli yomg‘ir (vaqti-vaqti bilan)",
        "heavy rain": "🌧️🌧️ Kuchli yomg‘ir",
        "light freezing rain": "❄️🌧️ Yengil muzli yomg‘ir",
        "moderate or heavy freezing rain": "❄️🌧️ Kuchli yoki o‘rtacha muzli yomg‘ir",
        "light sleet": "🌨️ Yengil qor aralash yomg‘ir",
        "moderate or heavy sleet": "🌨️🌨️ Kuchli qor aralash yomg‘ir",
        "patchy light snow": "🌨️ Yengil qor (ba'zida)",
        "light snow": "❄️ Yengil qor",
        "patchy moderate snow": "🌨️ O‘rtacha qor (ba'zida)",
        "moderate snow": "🌨️ O‘rtacha qor",
        "patchy heavy snow": "❄️❄️ Kuchli qor (ba'zida)",
        "heavy snow": "❄️❄️ Kuchli qor",
        "ice pellets": "🧊 Muz bo‘lakchalari",
        "light rain shower": "🌦️ Yengil yomg‘ir yog‘ishi",
        "moderate or heavy rain shower": "🌧️🌦️ Kuchli yomg‘ir yog‘ishi",
        "torrential rain shower": "🌧️🌧️🌧️ Jala",
        "light sleet showers": "🌨️ Yengil qor-yomg‘ir yog‘ishi",
        "moderate or heavy sleet showers": "🌨️🌨️ Kuchli qor-yomg‘ir yog‘ishi",
        "light snow showers": "🌨️ Yengil qor yog‘ishi",
        "moderate or heavy snow showers": "🌨️🌨️ Kuchli qor yog‘ishi",
        "light showers of ice pellets": "🧊 Yengil muz bo‘lakchalari yog‘ishi",
        "moderate or heavy showers of ice pellets": "🧊🧊 Kuchli muz bo‘lakchalari yog‘ishi",
        "patchy light rain with thunder": "⛈️ Yengil yomg‘ir va momaqaldiroq",
        "moderate or heavy rain with thunder": "⛈️⛈️ Kuchli yomg‘ir va momaqaldiroq",
        "patchy light snow with thunder": "🌩️❄️ Yengil qor va momaqaldiroq",
        "moderate or heavy snow with thunder": "🌩️❄️❄️ Kuchli qor va momaqaldiroq"
    }

}
